url: "https://ethesaurus.holusion.com"
baseurl: ""
title: "eThesaurus"

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: "fr"
    values:
      lang: "fr"
  - scope:
      path: "en"
    values:
      lang: "en"
  
  - scope:
      path: "fr/items"
    values:
      layout: "item"
  - scope:
      path: "en/items"
    values:
      layout: "item"

  - scope:
      path: "fr/doc"
    values:
      layout: "doc-page"
      type: doc
  - scope:
      path: "en/doc"
    values:
      layout: "doc-page"
      type: doc